### ISSUE TITLE
the amazing audio engine?

### ISSUE THREAD

**Issue by davut5** [arielelkin/SwiftyAudio#2]

**Comment by arielelkin** [comment]
Hi! What exactly is your question?

**Comment by davut5** [comment]
http://forum.theamazingaudioengine.com/discussion/1058/how-to-apply-filters-to-microphone-input#latest

**Comment by davut5** [comment]
i know only use Reverb effect. but i want to make 4 button echo, radio, chorus , reverb effect to my voice.
how can i do that?  Effects will works only for Headphone.

**Comment by arielelkin** [comment]
If you run the project in xcode, you'll be able to hear your voice modified in real time using a distortion effect and a reverb effect. You can follow the patterns to add the echo and chorus effects you want. 

The code in this repository will show you how to do that using AVAudioEngine, which is Apple's API for real-time audio. 

The Amazing Audio Engine is a different API. You can accomplish your goals with either API.

**Comment by davut5** [comment]
thank you so much now. now i understood. i know ı spent your time please dont angry to me, 
how can i make control the volume for mic input?

**Comment by arielelkin** [comment]
you can set the `volume` property on the `inputNode`: 

```
let input = engine.inputNode!
input.volume = 0.4
```

**Comment by arielelkin** [comment]
by the way, i just migrated the project to Swift 2, it should build and run fine on Xcode 7+ now.
